Repository habitat-sh/core, pull requests merged in 2018-10, with the labels that each got.

#71 Update Cargo.lock and make necessary changes for new users crate API
  Cargo.lock
  components/core/src/os/users/linux.rs
Labels: X-fix

#70 rework permissions into separate APIs for linux and windows
  Cargo.lock
  components/core/Cargo.toml
  components/core/src/crypto/keys/mod.rs
  components/core/src/crypto/mod.rs
  components/core/src/lib.rs
  components/core/src/os/filesystem/linux.rs
  components/core/src/os/filesystem/mod.rs
  components/core/src/os/filesystem/windows.rs
  components/core/src/util/mod.rs
  components/core/src/util/posix_perm.rs
  components/core/src/util/win_perm.rs
Labels: C-feature, E-less-easy, I-windows, L-rust

#75 When multiple signals are received, return them in order; don't drop any
  components/core/src/os/signals/unix.rs
Labels: X-fix

#74 [ci] Update to Rust 1.29.1.
  .travis.yml
Labels: A-builder, A-cli, A-exporter, A-launcher, A-supervisor, C-bug, E-easy, I-linux, I-macOS, I-windows, L-rust, V-devx
