Repository habitat-sh/core, pull requests merged in 2018-03, with the labels that each got.

#8 Add function to decrypt with a given set of keys instead of using the key cache dir
  components/core/src/crypto/keys/box_key_pair.rs
  components/core/src/crypto/keys/mod.rs
  components/core/src/crypto/keys/sig_key_pair.rs
Labels: enhancement

#12 Use a backslash for windows FS_ROOT and PKG_PATH
  components/core/src/fs.rs
  components/core/src/os/process/windows_child.rs
Labels: A-supervisor, C-bug, E-easy, I-windows, L-rust

#17 [core] Implement `Cow<'a, PackageIdent>` for `PackageIdent`.
  components/core/src/package/ident.rs
Labels: A-cli, A-exporter, A-supervisor, C-feature, E-easy, L-rust, V-devx
