Repository habitat-sh/core, pull requests merged in 2018-07, with the labels that each got.

#39 [ci,rustfmt] Formatting due to rustfmt 0.6.1 release in Rust 1.27.0.
  .travis.yml
  components/core/src/crypto/keys/box_key_pair.rs
  components/core/src/crypto/keys/mod.rs
  components/core/src/crypto/keys/sig_key_pair.rs
  components/core/src/crypto/keys/sym_key.rs
  components/core/src/os/process/windows_child.rs
  components/core/src/os/users/mod.rs
  components/http-client/src/api_client.rs
Labels: A-builder, A-cli, A-exporter, A-launcher, A-supervisor, C-chore, E-easy, I-linux, I-macOS, I-windows, L-rust, V-devx

#42 [core] Introduce a new `x86_64-linux-kernel2` `PackageTarget`.
  components/core/src/package/target.rs
Labels: A-builder, A-cli, A-exporter, A-supervisor, C-feature, E-easy, I-linux, L-rust, V-bldr, V-devx, V-sup, X-feature

#43 [ci] Update to Rust 1.27.1.
  .travis.yml
Labels: C-chore, E-easy, I-linux, I-macOS, I-windows

#45 only trim trailing $ from windows account check if it is the local machine account
  components/win-users/src/account.rs
Labels: A-supervisor, C-bug, E-easy, I-windows, L-rust, P-1
