Repository habitat-sh/core, pull requests merged in 2018-08, with the labels that each got.

#48 update all cargo deps
  Cargo.lock
  components/win-users/src/account.rs
Labels: C-chore, E-easy, L-rust

#49 Add the ability to handle SIGHUP
  components/core/src/os/process/linux.rs
  components/core/src/os/signals/mod.rs
Labels: X-feature

#51 [ci] Reimplement lint.sh program for better resilience.
  components/core/src/package/install.rs
  support/ci/lint.sh
Labels: C-chore, E-less-easy, I-linux, I-macOS, L-shell, V-infra

#50 [ci,rustfmt] Formatting due to rustfmt 0.8.2 in Rust 1.28.0.
  .travis.yml
  components/core/src/crypto/keys/box_key_pair.rs
  components/core/src/crypto/keys/mod.rs
  components/core/src/event.rs
  components/core/src/os/process/windows_child.rs
  components/core/src/package/archive.rs
  components/core/src/package/ident.rs
  components/core/src/package/install.rs
  components/core/src/package/metadata.rs
  components/http-client/src/net.rs
Labels: A-builder, A-cli, A-exporter, A-launcher, A-supervisor, C-chore, E-easy, I-linux, I-macOS, I-windows, L-rust, V-devx
