Repository habitat-sh/core, pull requests merged in 2018-12, with the labels that each got.

#92 Add secure_eq for timing-attack-resistant secret checking
  Cargo.lock
  components/core/Cargo.toml
  components/core/src/crypto/mod.rs
  components/core/src/lib.rs
Labels: X-feature

#93 cargo update post 0.70.0 release
  Cargo.lock
Labels: Expeditor: Exclude from Changelog

#100 [http-client] Lint and style updates
  Cargo.lock
  components/http-client/Cargo.toml
  components/http-client/src/api_client.rs
  components/http-client/src/error.rs
  components/http-client/src/lib.rs
  components/http-client/src/net.rs
  components/http-client/src/proxy.rs
  components/http-client/src/util.rs
Labels: A-cli, A-exporter, A-supervisor, C-chore, E-easy, I-linux, I-macOS, I-windows, L-rust, V-bldr, V-devx, V-sup
