Repository habitat-sh/core, pull requests merged in 2019-03, with the labels that each got.

#126 Remove output module to be transferred to habitat repo
  Cargo.lock
  components/core/Cargo.toml
  components/core/src/fs.rs
  components/core/src/lib.rs
  components/core/src/output.rs
  components/win-users/Cargo.toml
Labels: A-launcher, A-supervisor, C-bug, E-less-easy, L-rust, X-fix

#136 Cargo update following release 0.78.0
  Cargo.lock
Labels: Expeditor: Exclude from Changelog

#135 Fix clippy lints
  Makefile
  components/core/src/crypto/keys/box_key_pair.rs
  components/core/src/crypto/keys/mod.rs
  components/core/src/crypto/keys/sig_key_pair.rs
  components/core/src/crypto/keys/sym_key.rs
  components/core/src/event.rs
  components/core/src/fs.rs
  components/core/src/lib.rs
  components/core/src/os/process/linux.rs
  components/core/src/os/users/linux.rs
  components/core/src/package/archive.rs
  components/core/src/package/ident.rs
  components/core/src/package/install.rs
  components/core/src/package/list.rs
  components/core/src/package/metadata.rs
  components/core/src/package/mod.rs
  components/core/src/package/target.rs
  components/win-users/build.rs
Labels: Expeditor: Exclude from Changelog

#143 Remove offensively-named config keys in favor of updated versions
  components/core/tests/fixtures/test_package/default.toml
Labels: X-fix

#144 Adds more build_dep and build_tdep functionality
  components/core/src/package/archive.rs
  components/core/src/package/install.rs
Labels: C-feature, V-devx
